### PR TITLE
Adding test files

### PR DESCRIPTION
**Pull request by theGramburglar**

### CODE REVIEW

**Comment by Domanic** [comment]
Looks like you're missing the output for the big grid tests. Did you forget them? If you don't have them please let me know, I'll merge what you have as is.

Also you should have a dash after your EID in the file names.

**Comment by Domanic** [comment]
Can you please fix the file names?

**Comment by theGramburglar** [comment]
I'm actually going to have to submit this late. Can we cancel this PR so I can submit the correct one tomorrow?

**Comment by Domanic** [comment]
Sure, go ahead and close this request

**Pull request closed without merging**
